api/config/custom-environment-variables.json
api/config/default.json
api/package.json
api/src/lib/controllers/auth/auth.js
api/src/lib/controllers/auth/index.js
api/src/lib/controllers/index.js
api/src/lib/controllers/logs/basics.js
api/src/lib/controllers/logs/index.js
api/src/lib/controllers/logs/upload.js
api/src/lib/services/elastic.js
api/src/lib/services/mail.js
api/yarn.lock
docker-compose.yml
front/public/assets/css/app.css
front/src/auth/index.js
front/src/components/Profile.vue

Changes :
- Users are now stored as native ES users.
- Implemented mailing for the welcome message (with initial password) and password recovery.
- Possibility to change password through the profile page.
- API routes now protected depending on user roles.

Permissions

---

front/pages/partners.vue

And great job for partners ECs !
:+1:

add <abbr> for ECs and replace index by ezmesure

---

api/lib/controllers/auth/auth.js
api/lib/controllers/auth/index.js
api/lib/controllers/files/actions.js
api/lib/controllers/files/index.js
api/lib/controllers/index.js
api/lib/controllers/logs/basics.js
api/lib/controllers/logs/index.js
api/lib/controllers/logs/upload.js
api/lib/controllers/partners/actions.js
api/lib/controllers/partners/index.js
api/lib/controllers/providers/actions.js
api/lib/controllers/providers/index.js
api/lib/services/validator.js
api/package-lock.json
api/package.json
api/server.js
front/components/FileList.vue
rp/shibboleth/shibboleth2.dist.xml

Changes
######
- validate all inputs
- save direct uploads to files
- migrate to koa@2
- Fix CRU metadata

Validation

---

front/pages/index.vue

because for me, the current text on the home is too too small :smile:

bigger ezmesure description on the home

---

api/lib/controllers/contact/actions.js
api/lib/controllers/contact/index.js
front/locales/en.json
front/locales/fr.json
front/pages/contact-us.vue
templates/contact.mjml
templates/contact.txt

Contact form

---

api/lib/controllers/indices/actions.js
api/lib/controllers/indices/index.js
api/lib/controllers/openapi.json
api/lib/controllers/spaces/actions.js
api/lib/controllers/spaces/index.js
api/lib/controllers/users/actions.js
api/lib/controllers/users/index.js
api/lib/services/kibana.js

Added three new deletion routes:

Deletion routes

---

api/lib/controllers/openapi.json
api/lib/controllers/users/actions.js

Added ``size`` to increase the limit from 10 and ``source`` parameters to get more fields.

Get all users and more fields

---

docker-compose.debug.yml
docker-compose.migrate.yml
docker-compose.yml
ezmesure.env.sh
front/components/report/HealthDialog.vue
front/components/space/SpaceMenu.vue
front/components/space/ToolBar.vue
front/layouts/reporting.vue
front/locales/en.json
front/locales/fr.json
front/nuxt.config.js
front/package-lock.json
front/package.json
front/pages/admin/report.vue
front/pages/files.vue
front/pages/report.vue
front/plugins/ezreeport.js
rp/apache2/sites-available/default-ssl-no-shib.conf
rp/apache2/sites-available/default-ssl.conf

Includes :
- RP Configuration
- docker-compose (prod, migrate & dev) modifications
- 2 new tabs in "my space"
- "My reports", usable by all users to track current reports
- "ezREEPORT", in "Adminstration" (so only usable for admins) to manage advanced concepts (like templates, crons & queues)
- 1 popup
- To track ezREEPORT health

feat(front): ezREEPORT integration

---

api/config/custom-environment-variables.json
api/config/default.js
api/lib/hooks/utils.js
api/lib/services/promises.js
api/lib/services/sync/elastic.js
api/lib/services/sync/ezreeport.js
api/lib/services/sync/kibana.js
api/server.js

- Repositories roles are now dependant on insitution
- Add a cron to sync Elastic and Kibana

feature(api): sync for Elastic and Kibana

---

front/components/SpacesManager.vue

fixes default value for space name and creating space (as institution was null)

fix(front): fixed institution not beign fetched in SpacesManager

---

api/lib/controllers/sushi/actions.js
api/lib/hooks/harvest/jobs.js
api/lib/services/processors/harvest.js

while still updating Harvest table month by month

feat(api): jobs can harvest by period of multiple months

---

front/components/institutions/InstitutionsFiltersDrawer.vue
front/components/users/UsersFiltersDrawer.vue
front/locales/en.json
front/locales/fr.json
front/pages/admin/institutions.vue
front/pages/admin/users.vue

- institutions advanced filters with search compatibility
- institutions dynamic count when searching/filtering
- user filters no longer spam events

feature(front): added institution filters

---

front/components/MemberSearch.vue

feat(front): added more info when adding members

---

front/components/users/UsersFiltersDrawer.vue
front/locales/en.json
front/locales/fr.json
front/pages/admin/users.vue

now showing clearly which fields searchbar is using

feat(front): added search into users filters

---

api/lib/controllers/users/actions.js
front/components/MemberSearch.vue

- no longer needs to be admin to see mail and institutions when adding members
- when admin you can click on an institution to go to it's page

feature: more infos when adding members for every user and links to institutions pages

---

front/components/institutions/InstitutionsFiltersDrawer.vue
front/locales/en.json
front/locales/fr.json
front/pages/admin/institutions.vue

added no contacts, added exlusive mode, splitted services into smalled filters

feat(front): added new institutions filters

---

api/lib/controllers/institutions/actions.js
api/lib/controllers/repositories/actions.js
api/lib/controllers/repositories/index.js
api/lib/controllers/users/actions.js
api/lib/entities/repository-permissions.dto.js
api/lib/services/auth.js
api/lib/services/metrics.js
api/prisma/schema.prisma
api/test/features/repositories/create.test.js
api/test/features/repositories/delete.test.js
api/test/features/repositories/permissions/create.test.js
api/test/features/repositories/permissions/delete.test.js
api/test/features/repositories/permissions/update.test.js
api/test/features/repositories/read.test.js
api/test/features/repositories/update.test.js
api/test/setup/repositories.js
front/components/MemberRepoPermissions.vue
front/components/RepositoriesManager.vue

- dropped repos ids to simplify things
- fixed nested imports on users & institutions

feature: drop repos id

---

front/components/EndpointForm.vue
front/components/file/FileUploader.vue
front/components/institutions/JoinInstitutionDialog.vue
front/locales/en.json
front/locales/fr.json
front/pages/activate.vue
front/pages/kibana.vue
front/pages/password/reset.vue
front/pages/token.vue

v-html are often a vector of XSS attacks

fix(front): removed all v-html

---

front/components/MemberSearch.vue
front/components/ParentManager.vue
front/components/SubInstitutionsManager.vue
front/locales/en.json
front/locales/fr.json
front/pages/institutions/_id/index.vue

feature(vue): added a way to add parent institutions

---

api/lib/controllers/auth/auth.js
api/lib/controllers/auth/index.js
front/pages/kibana.vue

- reset link is now space dependent
- spaces and repos permissions are in profile

feat: added default space to user to kibana link

---

front/pages/institutions/_id/sushi.vue

feat(front): added sort on sushi endpoint status

---

front/locales/en.json
front/locales/fr.json
front/pages/myspace.vue

hiding infos if not present, made with card, list repos and spaces

feat(front): redone myspace page

---

front/pages/admin/institutions.vue

feat(front): validate institution in one click

---

front/components/RepositoriesManager.vue
front/components/SubInstitutionsManager.vue
front/components/repositories/ReposFiltersDrawer.vue
front/components/repositories/RepositoriesCreateForm.vue
front/components/repositories/RepositoriesInstitutionsDialog.vue
front/components/repositories/RepositoriesInstitutionsManager.vue
front/locales/en.json
front/locales/fr.json
front/pages/admin/repositories.vue

- Repositories filters
- Link institutions to a given repositories (from repositories list)
- Can create repositories from dedicated page
- Autocomplete when linking a repository to an institution

feat(front): finished repostiory page

---

front/components/ItemTree.vue
front/components/MemberUpdateDialog.vue
front/pages/institutions/_id/members.vue

- Refactored checkboxes for roles
- Added role "guest"
- Added searchbar for memebers

feat(front): minor ehancements on members page

---

api/lib/controllers/sushi-endpoints/actions.js
api/lib/controllers/sushi-endpoints/index.js
api/lib/entities/sushi-endpoints.dto.js
front/components/sushis/CredentialDialog.vue
front/locales/en.json
front/locales/fr.json
front/pages/admin/endpoints.vue
front/pages/admin/repositories.vue
front/pages/admin/users.vue

feat(front): added list of credentials for each endpoint

---

api/lib/controllers/institutions/actions.js
api/lib/controllers/institutions/index.js
api/lib/controllers/repositories/actions.js
api/lib/controllers/repositories/index.js
api/lib/controllers/users/actions.js
api/lib/controllers/users/index.js
api/lib/services/sync/ezreeport.js
api/lib/services/sync/index.js
front/components/SyncCard.vue
front/components/space/SpaceMenu.vue
front/locales/en.json
front/locales/fr.json
front/pages/admin/sync.vue

- Adjusted sync results from ezREEPORT (needs ezREEPORT `v1.0.0-beta.30`)
- Added validation filter for institutions
- Added pagination for repositories and users
- Only available for admins

feat: added sync overview page

---

front/locales/fr.json

fix(front): fixed issues with french description of sync

---

front/locales/en.json
front/locales/fr.json
front/pages/admin/users.vue

feat(front): now copy list of mails in clipboard instead of a mailto link

---

front/components/ProgressCircularStack.vue
front/components/SyncCard.vue
front/components/filters-form/BooleanFilter.vue
front/components/filters-form/ExclusiveBtnFilter.vue
front/components/filters-form/RangeFilter.vue
front/components/filters-form/SelectFilter.vue
front/components/institutions/InstitutionsFiltersDrawer.vue
front/pages/admin/institutions/index.vue

feat(front): added credentials connection status to institution list

---

api/lib/utils/sushi-definitions-patched.js

feat(api): soften report validation

---

front/components/LocalDate.vue
front/components/endpoints/EndpointDisabledIcon.vue
front/components/harvest/HarvestJobTable.vue
front/components/sushis/CredentialHarvestState.vue

Moved from "PPPpp" to "PPPp" because we don't really need to show seconds everywhere

feat(front): changed default format of LocalDate

---

api/lib/controllers/kibana-spaces/actions.js
api/lib/controllers/kibana-spaces/index.js
api/lib/controllers/openapi.json
api/lib/controllers/repositories/actions.js
api/lib/controllers/repositories/index.js

Partially solves the issue with permissions not beign imported
> [!NOTE]
> institutions and/or members should be imported first if `institutions` and/or `permissions` are provided with the spaces/repositories

feature(api): support space and repositories imports

---

api/lib/controllers/harvests-sessions/actions.js
api/lib/controllers/openapi.json
api/lib/entities/harvest-session.service.js

- **feat(api): create jobs in bulk when starting harvest**
- **feat(api): stop jobs in bulk when stopping harvest**

feat(api): start/stopping harvest is now done via bulk

---

api/lib/controllers/openapi.json
api/lib/entities/sushi-endpoints.dto.js
api/prisma/schema.prisma
front/components/filters/Select.vue
front/components/sushi/Form.vue
front/components/sushiEndpoint/Details.vue
front/components/sushiEndpoint/Filters.vue
front/components/sushiEndpoint/Form.vue
front/components/sushiEndpoint/Select.vue
front/components/sushiEndpoint/VersionsChip.vue
front/i18n/locales/en.yaml
front/i18n/locales/fr.yaml
front/pages/admin/endpoints/index.vue
front/pages/myspace/institutions/[id]/sushi.vue
front/utils/stateColors.js

feat: added support of multiple COUNTER versions for endpoints

---

api/lib/hooks/harvest/jobs.js
front/i18n/locales/en.yaml
front/i18n/locales/fr.yaml
front/utils/stateColors.js

feat: added "missing" harvest status

---

front/components/skeleton/SpaceMenu.vue
front/i18n/locales/en.yaml
front/i18n/locales/fr.yaml
front/pages/myspace/profile.vue

feat(front): added form to change password from ezMESURE

---

api/lib/services/processors/harvest/index.js
api/lib/services/processors/harvest/steps/download.js

Mainly inspired from sushi connection tests, harvesting set "unauthorized" status if an auth error occurs.
It merges found exceptions and returns last code found.

feat(api): updating sushi connection status on harvest

---

front/components/ProgressLinearStack.vue
front/components/sushiHarvest/StateChip.vue
front/components/sushiHarvest/session/Progress.vue
front/i18n/locales/en.yaml
front/i18n/locales/fr.yaml
front/pages/admin/endpoints/[id].vue
front/pages/myspace/institutions/[id]/sushi.vue

feat(front): added progress bars to preview harvest matrix

---

api/lib/controllers/harvests-sessions/actions.js
api/lib/controllers/openapi.json
api/lib/entities/harvest-session.dto.js
api/lib/hooks/harvest/harvest-session.js
api/prisma/schema.prisma
front/components/sushiHarvest/session/Header.vue
front/i18n/locales/en.yaml
front/i18n/locales/fr.yaml

feat: add an option to prevent mail on harvest session end

---

front/components/institution/Form.vue
front/components/repository/AutoComplete.vue
front/components/sushi/Form.vue
front/components/sushiEndpoint/Form.vue
front/components/sushiEndpoint/ReportCombobox.vue
front/i18n/locales/en.yaml
front/i18n/locales/fr.yaml

Add tag management in the institution form

feat(front): add tag management in the institution form
